lib/screener_web/router.ex
defmodule ScreenerWeb.Router do
  use ScreenerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ScreenerWeb do
    pipe_through :browser # Use the default browser stack
    get "/stocks", StockController, :index
    get "/stocks/:ticker/history/", HistoryController, :show
    get "/stocks/:ticker/quotes/", StockQuoteController, :show
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", ScreenerWeb do
  #   pipe_through :api
  # end
end

lib/screener/application.ex
defmodule Screener.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Screener.Repo, []),
      # Start the endpoint when the application starts
      supervisor(ScreenerWeb.Endpoint, []),
      # Start your own worker by calling: Screener.Worker.start_link(arg1, arg2, arg3)
      # worker(Screener.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Screener.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ScreenerWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/screener/repo.ex
defmodule Screener.Repo do
  use Ecto.Repo, otp_app: :screener

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/screener_web/controllers/history_controller.ex
defmodule ScreenerWeb.HistoryController do
  alias ScreenerWeb.Controllers.Helpers
  alias ScreenerWeb.Models.Helpers.API, as: Model
  use ScreenerWeb, :controller

  def show(conn, %{"ticker" => ticker}) do
    results = Model.get_stock_quotes(ticker)

    response =
    case results do
      {:error, reason} -> Helpers.handle_error(reason)
      {:ok, quotes} -> Helpers.get_quotes_with_indicators(quotes)
    end

    render conn, "show.html", response: response
  end

end

lib/screener_web/controllers/page_controller.ex
defmodule ScreenerWeb.PageController do
  use ScreenerWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
  
end

lib/screener_web/controllers/stock_controller.ex
defmodule ScreenerWeb.StockController do
  alias ScreenerWeb.Symbol
  use ScreenerWeb, :controller

  def index(conn, _params) do
    symbols = Symbol.get_symbols |> Enum.sort

    render conn, "index.html", symbols: symbols
  end

end

lib/screener_web/controllers/stock_quote_controller.ex
defmodule ScreenerWeb.StockQuoteController do
  alias ScreenerWeb.Controllers.Helpers
  alias ScreenerWeb.Models.Helpers.API, as: Model
  use ScreenerWeb, :controller

  def show(conn, %{"ticker" => ticker}) do
    results = Model.get_stock_quotes(ticker)

    response =
    case results do
      {:error, reason} -> Helpers.handle_error(reason)
      {:ok, quotes} -> Helpers.get_quote_with_indicators(quotes)
    end

    render conn, "show.html", response: response
  end

end

lib/screener_web/views/error_view.ex
defmodule ScreenerWeb.ErrorView do
  use ScreenerWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/screener_web/views/layout_view.ex
defmodule ScreenerWeb.LayoutView do
  use ScreenerWeb, :view
end

lib/screener_web/views/page_view.ex
defmodule ScreenerWeb.PageView do
  use ScreenerWeb, :view
end

lib/screener_web/views/shared/technical_indicators_view.ex
defmodule ScreenerWeb.TechnicalIndicatorsView do
  use ScreenerWeb, :view
  import ScreenerWeb.Views.Helpers
end

lib/screener_web/views/stock_quote_view.ex
defmodule ScreenerWeb.StockQuoteView do
  use ScreenerWeb, :view

  def capitalize(field) do
    String.capitalize(field)
  end

  # api comes back as: 1.) close
  def remove_non_letter_chars(field) do
    field
    |> String.split(" ")
    |> Enum.at(1)
  end

  def to_int(number) do
    { integer, _ } = Float.parse(number)
    Float.round(integer, 3)
  end

end

lib/screener_web/views/stock_view.ex
defmodule ScreenerWeb.StockView do
  use ScreenerWeb, :view

  def char_to_string(x) do
    List.to_string([x])
  end

end

lib/screener_web/templates/api_errors/api_errors.html.eex
<p> Sorry, there was an error! </p>
<p> The issue is most likely with your ticker symbol. Please verify it is still valid. </p>

<h5> Reason: </h5>
<p> <%= elem(@response.data, 1) %> </p>

lib/screener_web/templates/history/show.html.eex
<div> <h1>  Ticker History: </h1> </div>

<%= case @response.data do %>
  <%= {:error, reason} -> %>
    <%= render ScreenerWeb.APIErrorsView, "api_errors.html", assigns %>
  <% _ -> %>
    <div>
      <table>
        <tr>
          <th>Open</th>
          <th>High</th>
          <th>Low</th>
          <th>Close</th>
          <th>Volume</th>
        </tr>
        <tr>
       <%= for {date, quote_info} <- @response.data do %>
        <td> <%= date %> </td>
        <%= for {_quote_field, value} <- quote_info do %>
          <td> <%= to_int(value) %> </td>
        <% end %>
        </tr>
      <% end %>
    </table>
  </div>

  <%= render ScreenerWeb.TechnicalIndicatorsView, "technical_indicators.html", assigns %>
<% end %>

lib/screener_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TA Screener</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="/stocks">Home</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/screener_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

lib/screener_web/templates/stock/index.html.eex
<h1> Get a Quote: </h1>


<table>
  <tr>
    <th>Ticker Symbol</th>
  </tr>
  <%= for s <- @symbols do %>
  <tr>
    <td><%= s %></td>
    <td><%= link "Get Quote", to: stock_quote_path(@conn, :show, char_to_string(s)) %></td>
    <td><%= link "Historical Quote", to: history_path(@conn, :show, char_to_string(s)) %></td>
  </tr>
  <% end %>
</table>

lib/screener_web/templates/stock_quote/show.html.eex
<div> <h1>  Ticker Quote: </h1> </div>

<%= case @response.data do %>
  <%= {:error, reason} -> %>
    <%= render ScreenerWeb.APIErrorsView, "api_errors.html", assigns %>
  <% _ -> %>
    <div>
       <%= for { date, quote_info } <- @response.data do %>
        <h4>  <%= date %> </h4>
        <%= for {quote_field, value} <- quote_info do %>
          <p> <%= remove_non_letter_chars(quote_field) |> capitalize %>: <%= to_int(value) %> </p>
        <% end %>
      <% end %>
    </div>

    <%= render ScreenerWeb.TechnicalIndicatorsView, "technical_indicators.html", assigns %>
<% end %>

lib/screener_web/templates/technical_indicators/technical_indicators.html.eex
<div>
  <h5> Technical Indicators: </h>
    <%= for {indicator, values} <- @response.technical_indicators do %>
      <h6>  <%= indicator %>: <%= Enum.map(values, fn {field, value} -> "#{field}: #{round_int(value)} " end) %> </h6>
    <% end %>
</div>